### ISSUE TITLE
Can't find libobs when building against OBS 28

### ISSUE THREAD

**Issue by rmnvgr** [flathub/com.obsproject.Studio.Plugin.waveform#6]
@phandasm I tried building Waveform 1.50-beta1 against OBS 28, but it failed with this error:

```
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.
```

OBS changed its CMake files since version 28, and the file is now `libobsConfig.cmake`.

Is there anything you can do on your side?

**Comment by phandasm** [comment]
Yeah the build system for plugins changed a bit from 27 to 28, I'm still trying to work out how to get it to build consistently across all platforms with both OBS 27 and 28 targets but I could hack in a workaround for linux if you need it sooner.

**Comment by rmnvgr** [comment]
Don't worry there's no rush, the current build still works in OBS 28.

**Comment by phandasm** [comment]
Should be fixed now.

**Comment by rmnvgr** [comment]
Yes it's perfectly working! Thank you!
